# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'solomon_client' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for solomon_client

  target 'solomon_client-tvOSTests' do
    inherit! :search_paths
    # Pods for testing

    pod 'GooglePlaces'
    pod 'GoogleMaps'
    pod 'GooglePlacePicker'
  end

  target 'solomon_clientTests' do
    inherit! :search_paths
    # Pods for testing

    pod 'GooglePlaces'
    pod 'GoogleMaps'
    pod 'GooglePlacePicker'
  end

end

target 'solomon_client-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for solomon_client-tvOS

  target 'solomon_client-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
    
    pod 'GooglePlaces'
    pod 'GoogleMaps'
    pod 'GooglePlacePicker'
  end

end
